### PR TITLE
Update WebStorm to 2017.1

### PR DESCRIPTION
**Pull request by CN-Zed**

### CODE REVIEW

**Comment by digitaldrummerj** [comment]
@CN-Zed thank you for the pull request.  would you like to be added as a maintainer of the webstorm Chocolatey package?

**Comment by CN-Zed** [comment]
Yes, I would.

**Comment by digitaldrummerj** [comment]
@CN-Zed give me a few days to get the Webstorm package moved to its own repository.  What is your Chocolatey.org user name?

**Comment by CN-Zed** [comment]
My Chocolatey.org user name is **zed**.

**Pull request merged**
